CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT,
  name TEXT,
  phone TEXT,
  cpf TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  email_verified INTEGER NOT NULL DEFAULT 0,
  email_verified_at TEXT
);

CREATE TABLE IF NOT EXISTS customer_addresses (
  id TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  label TEXT,
  recipientName TEXT,
  phone TEXT,
  zip TEXT NOT NULL,
  street TEXT NOT NULL,
  number TEXT NOT NULL,
  complement TEXT,
  district TEXT,
  city TEXT NOT NULL,
  uf TEXT NOT NULL,
  isDefault INTEGER NOT NULL DEFAULT 0,
  createdAt BIGINT NOT NULL,
  updatedAt BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_customer_addresses_user_id ON customer_addresses(user_id);
CREATE INDEX IF NOT EXISTS idx_customer_addresses_default ON customer_addresses(user_id, isDefault);

CREATE TABLE IF NOT EXISTS categories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  sortOrder INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  createdAt BIGINT NOT NULL,
  updatedAt BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT,
  price DOUBLE PRECISION NOT NULL,
  compareAtPrice DOUBLE PRECISION,
  stock INTEGER NOT NULL DEFAULT 0,
  sku TEXT,
  active INTEGER NOT NULL DEFAULT 1,
  categoryId TEXT,
  subCategoryId TEXT,
  color TEXT,
  inMovingShowcase INTEGER NOT NULL DEFAULT 0,
  featured INTEGER NOT NULL DEFAULT 0,
  deal INTEGER NOT NULL DEFAULT 0,
  isCollection INTEGER NOT NULL DEFAULT 0,
  isWeeklyFavorite INTEGER NOT NULL DEFAULT 0,
  externalSource TEXT,
  externalSku TEXT,
  syncStock INTEGER NOT NULL DEFAULT 0,
  syncPrice INTEGER NOT NULL DEFAULT 0,
  lastSyncedAt BIGINT,
  createdAt BIGINT NOT NULL,
  updatedAt BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_products_active ON products(active);
CREATE INDEX IF NOT EXISTS idx_products_slug ON products(slug);
CREATE INDEX IF NOT EXISTS idx_products_categoryid ON products(categoryId);
CREATE INDEX IF NOT EXISTS idx_products_featured ON products(featured);
CREATE INDEX IF NOT EXISTS idx_products_deal ON products(deal);

CREATE TABLE IF NOT EXISTS product_images (
  id TEXT PRIMARY KEY,
  productId TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  alt TEXT,
  sortOrder INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_product_images_pid ON product_images(productId);

CREATE TABLE IF NOT EXISTS product_category_links (
  productId TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  categoryId TEXT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  createdAt BIGINT NOT NULL,
  PRIMARY KEY (productId, categoryId)
);

CREATE INDEX IF NOT EXISTS idx_product_category_links_categoryid ON product_category_links(categoryId);

CREATE TABLE IF NOT EXISTS wishlist_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  createdAt BIGINT NOT NULL DEFAULT 0,
  UNIQUE(user_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_wishlist_user_id ON wishlist_items(user_id);

CREATE TABLE IF NOT EXISTS external_product_blocks (
  source TEXT NOT NULL,
  externalSku TEXT NOT NULL,
  createdAt BIGINT NOT NULL,
  PRIMARY KEY (source, externalSku)
);

CREATE TABLE IF NOT EXISTS integration_cursors (
  id TEXT PRIMARY KEY,
  page INTEGER NOT NULL DEFAULT 1,
  "offset" INTEGER NOT NULL DEFAULT 0,
  updatedAt BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  createdAt BIGINT NOT NULL,
  status TEXT NOT NULL,
  paymentMethod TEXT NOT NULL,
  paymentJson TEXT,
  customerJson TEXT NOT NULL,
  customerEmail TEXT,
  addressJson TEXT,
  itemsJson TEXT NOT NULL,
  subtotal DOUBLE PRECISION NOT NULL,
  shippingAmount DOUBLE PRECISION NOT NULL DEFAULT 0,
  total DOUBLE PRECISION NOT NULL,
  statusHistoryJson TEXT,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  trackingCode TEXT,
  trackingCarrier TEXT,
  trackingUrl TEXT,
  paidNotifiedAt BIGINT,
  shippedNotifiedAt BIGINT,
  stockDeductedAt BIGINT
);

CREATE INDEX IF NOT EXISTS idx_orders_createdat ON orders(createdAt DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_customeremail ON orders(customerEmail);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);

CREATE TABLE IF NOT EXISTS request_rate_limits (
  key TEXT PRIMARY KEY,
  count INTEGER NOT NULL DEFAULT 0,
  resetAt BIGINT NOT NULL,
  updatedAt BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_request_rate_limits_resetat ON request_rate_limits(resetAt);
